// <auto-generated />
namespace CosmicCakes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogThemePost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogThemePost));
        
        string IMigrationMetadata.Id
        {
            get { return "201703162131456_BlogThemePost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
